### ISSUE TITLE
Serve requires factorio binary

### ISSUE THREAD

**Issue by gartou** [Palats/mapshot#12]
Why does the script requires the factorio binary when only serve-ing the web?

![image](https://user-images.githubusercontent.com/11245344/124116187-f1a03c00-da6e-11eb-84c5-a568708cb15c.png)

**Comment by Palats** [comment]
Hah indeed. It looks for the Factorio install to find the `script-output` directory. But as far as I can tell, it would be possible to just specify a base dir manually instead. I'll see to add a flag for that.

**Comment by Palats** [comment]
Release 0.0.13 should behave better. If I read your log correctly, it should now just work out of the box. If not, you can specify your script-output directory location with `--factorio_scriptoutput`.
