### ISSUE TITLE
Option ‘disable-prototype-history’ does not exist

### ISSUE THREAD

**Issue by AstraLuma** [Palats/mapshot#24]
Running Factorio 1.1.69 and Mapshot 0.0.14

[render.log](https://github.com/Palats/mapshot/files/9769902/render.log)

(I am trying to develop a container, but I don't think that's what's happening here?)

**Comment by Palats** [comment]
Ah, thanks for the report - it seems indeed the flag has been removed from recent releases. I haven't found a confirmation but https://forums.factorio.com/99385 strongly hints at it.

The flag is not particularly useful - it was just an attempt to make things start faster - so I'll just remove it.

**Comment by Palats** [comment]
There, [version 0.0.15](https://github.com/Palats/mapshot/releases/tag/0.0.15) removes the flag.
