### ISSUE TITLE
Surface setting not used

### ISSUE THREAD

**Issue by rdbruijne** [Palats/mapshot#30]
The setting to check which surfaces to render a map for isn't checked while rendering the map.
I'm not set up do test the changes myself, but the attached patch file could help.
[check_surface_setting_patch.txt](https://github.com/Palats/mapshot/files/10212982/check_surface_setting_patch.txt)

**Comment by Palats** [comment]
I'm not sure how I missed that in the [original commit](https://github.com/Palats/mapshot/commit/83f8ba8c74e50bc64e0b1c2f50a0b0a170b14174) but indeed that is not doing what is expected - thanks for noticing and providing a patch!  Not sure when exactly I'll have time to integrate it properly, but I'll get around to it.

**Comment by Palats** [comment]
There, the fix is available in version 0.0.17. Thanks again for the patch!
