### ISSUE TITLE
Thin lines visibles between tiles

### ISSUE THREAD

**Issue by Palats** [Palats/mapshot#4]
When using fractional zooms level, there are some lines which can be visible between tiles. This comes from  https://github.com/Leaflet/Leaflet/issues/3575 . There are some workaround in the bug which might work.

**Comment by cengbrecht** [comment]
Might upload to a webserver if you're curious. 
Its a 10Gb folder now, :P Figured out the quality settings and such that I like, but it does show the thin lines. 
![image](https://user-images.githubusercontent.com/1149435/105623095-41018280-5dd4-11eb-943c-d5ec0e31292f.png)

**Comment by cengbrecht** [comment]
Another guy in that thread mentioned that Leaflet is not really super good at support any more. 
And suggested https://openlayers.org/ openlayers as a strong alternative.
Any thoughts?

**Comment by cengbrecht** [comment]
Also, this post has an interesting workaround:
https://github.com/ngageoint/mapcache-electron/commit/53dcfa608f477d1ccd088320cf76de7b8ce8bc5f

**Comment by Palats** [comment]
Fix is not great - issues are still visible when unzooming a lot without reloading. Though it seems that it mostly does the trick when zoomed it, so we will go with that for now.

**Comment by Palats** [comment]
Release 0.0.11 has the workaround.
