### ISSUE TITLE
Question about the HTTP server

### ISSUE THREAD

**Issue by TheFrenchTechMan** [Palats/mapshot#44]
I was wondering if it was possible to modify which resolution of screenshots is being used for the served map, as I think my HTTP server is currently using a lower resolution than it can. Is it possible to edit a part of the JS script or HTML to change this? By the way, I'm using the `http.server` from Python, on Linux.

Thanks in advance for your response.

**Comment by Palats** [comment]
If using the generated html/js (incl. when using `mapshot serve`), it will provide a zoomable map - i.e., it will load a different set of tile when zoom/dezoom from the map. That means that most of the time, what makes sense to control is the maximum zoom level to generate - careful though, it can quickly increase in size and time to generate.

Which tiles are generated can be configured on the command line of `mapshot render` or from the mod interface when triggering from Factorio itself. The README has a few more details but roughly the main parameters are:
 - `--tilemin`: Size in in-game units of a tile for the most zoomed layer. Defaults to 64, use 32 or 16 to have a more zoomed in version. It generates tons of data.
 - `--tilemax`: Size in in-game units of a tile for the least zoomed layer. Defaults to 1024, and it does not really make sense to change it.
 - `--resolution`: Pixel size for generated tiles. Defaults to 1024. Increasing it (e.g., 2048) might increase the resolution of a single tile.
