### ISSUE TITLE
Factorio 2.0.8 Option ‘disable-audio’ does not exist 

### ISSUE THREAD

**Issue by antgeo** [Palats/mapshot#48]
I1023 04:25:22.523531      63 factorio.go:124] Running factorio with args: [--disable-audio --load-game /tmp/mapshot3599816298/save.zip --mod-directory /tmp/mapshot3599816298/mods]
Option ‘disable-audio’ does not exist

**Comment by cyrkul** [comment]
I guess you are running headless server, look at: [https://github.com/Palats/mapshot/issues/22](#22)

**Comment by Palats** [comment]
Indeed, as @cyrkul mentions, this is a symptom of using the headless version of Factorio. This is not supported, as this version lacks support for rendering graphics.
