### ISSUE TITLE
Pollution in the map now?

### ISSUE THREAD

**Issue by robertmassaioli** [Palats/mapshot#50]
Is it just me, or did pollution used to not show up in the map: https://factorio-maps.rmdir.app/app/save/2024-England/mapshot/429c1e97/

And now it does: https://factorio-maps.rmdir.app/app/save/2024-England/mapshot/c6c40e88/

**Comment by Palats** [comment]
I did not change anything in that regard. And the mod is using [Factorio API `take_screenshot`](https://lua-api.factorio.com/stable/classes/LuaGameScript.html#take_screenshot), so options are limited in any case.

Though looking the provided links - the only thing I see different are the darker spots. But those look quite a bit random and not matching pollution (which is also per chunk). Maybe that's just more Factorio cosmetic bits.

**Comment by Palats** [comment]
I've checked with basically an empty save - and the dark spots are there. I'll assume that it is a change in rendering & appearance introduced by Factorio 2.0. It does not react well with zooming/unzooming in mapshot, but there is not much I can do for that.

**Comment by robertmassaioli** [comment]
Fair enough, I might submit a bug report to Factorio directly then and see if I can't get them to turn off pollution clouds as an option at the very least.

**Comment by robertmassaioli** [comment]
Posted here: https://forums.factorio.com/viewtopic.php?f=7&t=119502&p=631551#p631551

**Comment by robertmassaioli** [comment]
Hey, apparently these are clouds @Palats and we can turn them off with this maybe? https://forums.factorio.com/viewtopic.php?t=85568&utm_source=perplexity

**Comment by Palats** [comment]
Oh, good catch indeed - and going through the LuaSurface might also be interesting for other things too.

I'm not sure I'll have time to do it in the next few days, but that does look promising indeed.

**Comment by Palats** [comment]
So, `show_clouds` does work. However,  I cannot just restore the value of `show_clouds` once the `take_screenshot` have been issued - it must be set to false until all the screenshots are finished. I'm not sure yet how I'm going to do that:
 - When triggering a one time screenshot from the CLI, there is an explicit step waiting for screenshots to be made. It should be possible to clean things there, though it would require some more structure than I have in my prototype.
 - When triggering from the `/mapshot` command, there is currently nothing blocking on getting screenshot. I could add it, but that would change the behavior - I need to check if that's acceptable.

**Comment by robertmassaioli** [comment]
That all makes sense, I'm just happy to hear that you have started looking into it. Thanks!

**Comment by Palats** [comment]
Version 0.0.26 should be hiding the clouds automatically when rendering from the CLI. For the in-game `/mapshot` command, I have failed to find a way to restore the clouds after the screenshots - it seems that waiting for the shots and an extra tick does not cut it.
