### ISSUE TITLE
Does this mod supports the content from Space Age DLC?

### ISSUE THREAD

**Issue by changchiyou** [Palats/mapshot#52]
Does this mod support displaying new content from Space Age DLC? I noticed it [now supports Factorio 2.0](https://github.com/Palats/mapshot/issues/49), but the example shown on [the website](https://mapshot.palats.xyz/) only displays Nauvis. This led me to wonder if space platformes/planets support is available.

**Comment by Palats** [comment]
Afaik, it should work. Mapshot already exports (by default) all surfaces, and that should include the platforms/planets. (haven't tested it as I don't have such a save handy though).
