### ISSUE TITLE
Feature Request: extra informations `Mapshot unique ID` from executing `mapshot info`

### ISSUE THREAD

**Issue by changchiyou** [Palats/mapshot#58]
I need additional information, particularly the `Mapshot unique ID`, to create a shell script that checks if the target folder already exists before proceeding. This will help prevent duplicate renders.

```
  17.962 Script @__mapshot__/control.lua:310: Unique ID: 6057eeb8
  17.963 Script @__mapshot__/control.lua:321: Map ID: b31aa8c5
  17.963 Script @__mapshot__/control.lua:70: Mapshot target mapshot/XI_1028/
  17.963 Script @__mapshot__/control.lua:71: Mapshot data target mapshot/XI_1028/d-6057eeb8/
  17.963 Script @__mapshot__/control.lua:72: Mapshot unique id 6057eeb8
```

I would be happy to contribute to this project, but my knowledge isn’t sufficient to do so. 😢

**Comment by Palats** [comment]
I'm not sure what you are asking for - you want to get some information when running something from the command line?

Taking a bit of step back - what it is you are trying to do / avoid overall? Is it something along the lines of "I want to be able to run `mapshot render` on a given save, and that it skips rendering if the output already exists" ?

**Comment by changchiyou** [comment]
> Is it something along the lines of "I want to be able to run `mapshot render` on a given save, and that it skips rendering if the output already exists" ?

Yes, that's what I want. However, I just discovered a few hours ago that I can use `md5sum` to check if the ZIP file has been modified, which allows me to avoid rendering it again.

**Comment by Palats** [comment]
Ah yes, indeed, a hash of the save would probably go 99% of the way. Fwiw, the hash can really only be calculated in Factorio Lua - thus require Factorio to run. We could imagine having the mod record the last mapshot that was generated (as part of the mod state - afaik, that's doable) and avoid regenerating. But in practice, it seems that you have your solution, so that's good like that for now :)
